# Generated by Django 3.2.16 on 2023-01-21 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=3)),
                ('line', models.IntegerField(default=0)),
                ('percent', models.FloatField(default=0.0)),
                ('winnings', models.FloatField(default=0.0)),
                ('payout', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso', models.CharField(max_length=3)),
                ('long_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PastGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=3)),
                ('home_score', models.IntegerField(default=0)),
                ('home_money_line', models.IntegerField(default=0)),
                ('away_team', models.CharField(max_length=3)),
                ('away_score', models.IntegerField(default=0)),
                ('away_money_line', models.IntegerField(default=0)),
                ('game_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=3)),
                ('long_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='TodayLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('away_team', models.CharField(max_length=3)),
                ('away_money_line', models.IntegerField(default=0)),
                ('home_team', models.CharField(max_length=3)),
                ('home_money_line', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_currency', models.CharField(max_length=3)),
                ('rate', models.FloatField(default=1.0)),
                ('last_update_time', models.DateTimeField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myap.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0.0)),
                ('buy_date', models.DateField()),
                ('iso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myap.currency')),
            ],
        ),
        migrations.CreateModel(
            name='AccountHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('currencies_visited', models.ManyToManyField(to='myap.Currency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
