# Generated by Django 3.2.16 on 2023-01-20 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountholder',
            name='currencies_visited',
        ),
    ]
