# Generated by Django 3.2.16 on 2023-01-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodayLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('away_team', models.CharField(max_length=3)),
                ('away_money_line', models.IntegerField(default=0)),
                ('home_team', models.CharField(max_length=3)),
                ('home_money_line', models.IntegerField(default=0)),
            ],
        ),
    ]
