# Generated by Django 3.2.16 on 2023-01-19 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myap', '0002_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=3)),
                ('home_score', models.IntegerField(default=0)),
                ('home_money_line', models.IntegerField(default=0)),
                ('away_team', models.CharField(max_length=3)),
                ('away_score', models.IntegerField(default=0)),
                ('away_money_line', models.IntegerField(default=0)),
                ('game_date', models.DateField()),
            ],
        ),
    ]
