# Generated by Django 3.2.16 on 2023-01-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myap', '0003_bets'),
    ]

    operations = [
        migrations.AddField(
            model_name='bets',
            name='percent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bets',
            name='winnings',
            field=models.IntegerField(default=0),
        ),
    ]
