# Generated by Django 3.2.16 on 2023-01-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myap', '0004_auto_20230121_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='bets',
            name='payout',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='bets',
            name='winnings',
            field=models.FloatField(default=0.0),
        ),
    ]
